# Site settings
title: Ronel Zapata
SEOTitle: Ronel Zapata
# header-icon: assets/images/header-icon.png
header-img: assets/images/main-banner.png
email: ronelzb@gmail.com
description: "This is my personal webpage where I show the latest projects I’m working on, you can find a little bit about me in the About section, if you have any comments/suggestion please let me know"
keyword: "RZ, Ronel Zapata, ronelzb, .NET, Java, Python, SQL Server, Full-Stack developer, Software engineer"
url: "https://ronelzb.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
gh-repo: "https://github.com/ronelzb/ronelzb.github.io" # your code repository

og-url: ronelzb.github.io

# Sidebar settings
#sidebar: true                        # whether or not using Sidebar.

# SNS settings
RSS: false
github_username:    ronelzb
facebook_username:  ronelzb
twitter_username:   ronelzb
linkedin_username: ronel-josé-zapata-beltrán-b86b2733
youtube_channelid: UCmN-__lazZj-vbY7PnAJ7WA

# Default output path for your pages (Mandatory for GitHub Pages if you use relative url)
permalink: pretty

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/

# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                              # use Github Flavored Markdown !important

# Google Analytics
#ga_track_id: 
#ga_domain: auto                          # The default is auto, if you don’t have your own domain name, you need to keep it at auto
ga_meas_id: 'G-84XP2BGW7K'

# Featured Tags
featured-tags: false                      # Whether to use the homepage tag
featured-condition-size: 1                # Only if the number of the same label is greater than this number, it will appear on the homepage

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Progressive Web Apps
chrome-tab-theme-color: "#000"
service-worker: true

nav_pages:
  - title: "Tags"
    url: "/tags"
  - title: "About"
    url: "/about"